### ISSUE TITLE
在封装思想和设计上还有待改进

### ISSUE THREAD

**Issue by GuoBinyong** [zrwusa/data-structure-typed#1]
实现的比较冗余，在封装思想和设计上还有待改进

**Comment by GuoBinyong** [comment]
比如 `HeapItem` 就是完全多余的一个设计，应该如下设计：
1. Heap 的操作对象可以是任务类型，类型通过泛型约束；
2. 暴露一个用于比较优先级的回调函数，可由用户自定义比较规则；

这种方式比 `HeapItem`  有以下优点：
1. 用户可以使用业务中的数据结构
2. 用户可以自定更复杂的比较规则：比如基于多个属性的比较 或 动态的比较
3. `HeapItem`  用类来实现稍身体增加了一些对象成员的命中难度 和 一点点的内存空间

**Comment by zrwusa** [comment]
> 比如 `HeapItem` 就是完全多余的一个设计，应该如下设计：
> 
> 1. Heap 的操作对象可以是任务类型，类型通过泛型约束；
> 2. 暴露一个用于比较优先级的回调函数，可由用户自定义比较规则；
> 
> 这种方式比 `HeapItem` 有以下优点：
> 
> 1. 用户可以使用业务中的数据结构
> 2. 用户可以自定更复杂的比较规则：比如基于多个属性的比较 或 动态的比较
> 3. `HeapItem`  用类来实现稍身体增加了一些对象成员的命中难度 和 一点点的内存空间

HeapItem: It seems like it might be a redundant implementation, and it may not be necessary. Let's carefully consider this.

Heap using generic constraints directly: Have you noticed that Heap doesn't implement much logic itself? It relies on PriorityQueue, which indeed directly uses generic constraints. In C++ and Java, PriorityQueue is commonly used directly. However, I think Heap should also be implemented this way to maintain a consistent code style.

Priority comparison callback: Although our PriorityQueue does implement the ability to pass a priority comparison function as a callback in the constructor, I agree that Heap should indeed provide a priority comparison function, as you suggested, to make it smoother for developers using only Heap.

Thank you for your feedback, and if you'd like to contribute, please leave a comment.

**Comment by zrwusa** [comment]
In version 1.36.0, we have redesigned the Heap and PriorityQueue to incorporate the suggestions made in this issue.

1. The operations of the Heap can now be performed on objects of any type, which is constrained by generics.

2. We have exposed a callback function for priority comparison, allowing users to customize the comparison rules.

3. We have removed the design of HeapItem.

**Comment by zrwusa** [comment]
In version 1.36.0, we have redesigned the Heap and PriorityQueue to incorporate the suggestions made in this issue.

The operations of the Heap can now be performed on objects of any type, which is constrained by generics.

We have exposed a callback function for priority comparison, allowing users to customize the comparison rules.

We have removed the design of HeapItem.
