### ISSUE TITLE
allow all list datatype 'delete' methods to accept null as an input argument

### ISSUE THREAD

**Issue by tonk777** [zrwusa/data-structure-typed#24]
Given the the list 'find' methods can return null it would be nice to be able to write ...

some_list.delete (some_list.find ((item) => item.some_value === find_value)) ;  // does not transpile as null not an acceptable argument type for 'delete'

... without having to filter out any null returned from 'find' before calling 'delete'.

Of course 'delete' receiving null is a do-nothing operation

**Comment by zrwusa** [comment]
> Given the the list 'find' methods can return null it would be nice to be able to write ...
> 
> some_list.delete (some_list.find ((item) => item.some_value === find_value)) ; // does not transpile as null not an acceptable argument type for 'delete'
> 
> ... without having to filter out any null returned from 'find' before calling 'delete'.
> 
> Of course 'delete' receiving null is a do-nothing operation

Thank you for your suggestion. We will support passing null values to the delete method in v1.38.5.
