### ISSUE TITLE
Infinite Loop on getAllPathsBetween

### ISSUE THREAD

**Issue by HuguesGauthier** [zrwusa/data-structure-typed#34]
**Describe the bug**

"undirected-graph-typed": "^1.41.3"

const vertex = p.getIntersection(routes);
const edges = p.getIntersectionNearestConnection( routes, vertex);

const graph = new UndirectedGraph();
for (const v of vertex) {
    graph.addVertex(v.name, v);
};

for (const e of edges) {
    const [s,d] = e;
    graph.addEdge( s.name, d.name, d.distanceFromParent );
};

const result = graph.getAllPathsBetween('Intersection_1','Intersection_5',true)

**infinite loop when calling the getAllPathsBetween.**

i have a i9-10900k i stop the process after 5m.

**Desktop (please complete the following information):**
 - OS: Win 11
 - - node v20.7.0

**Additional context**
files: 
Vertex
[SaltyGateStreetIntersections.json](https://github.com/zrwusa/data-structure-typed/files/13242883/SaltyGateStreetIntersections.json)
Edge:
[SaltyGateStreetConnections.json](https://github.com/zrwusa/data-structure-typed/files/13242882/SaltyGateStreetConnections.json)

**Comment by HuguesGauthier** [comment]
in this function i commented this line `visiting.set(cur, false)`; , and i got the good result.

```
getMinPathBetween(v1, v2, isWeight) {
        if (isWeight === undefined)
            isWeight = false;
        if (isWeight) {
            const allPaths = this.getAllPathsBetween(v1, v2);
            let min = Infinity;
            let minIndex = -1;
            let index = 0;
            for (const path of allPaths) {
                const pathSumWeight = this.getPathSumWeight(path);
                if (pathSumWeight < min) {
                    min = pathSumWeight;
                    minIndex = index;
                }
                index++;
            }
            return allPaths[minIndex] || null;
        }
        else {
            // BFS
            let minPath = [];
            const vertex1 = this._getVertex(v1);
            const vertex2 = this._getVertex(v2);
            if (!(vertex1 && vertex2)) {
                return [];
            }
            const dfs = (cur, dest, visiting, path) => {
                visiting.set(cur, true);
                if (cur === dest) {
                    minPath = [vertex1, ...path];
                    return;
                }
                const neighbors = this.getNeighbors(cur);
                for (const neighbor of neighbors) {
                    if (!visiting.get(neighbor)) {
                        path.push(neighbor);
                        dfs(neighbor, dest, visiting, path);
                        (0, utils_1.arrayRemove)(path, (vertex) => vertex === neighbor);               
                    }
                }
                //visiting.set(cur, false);
            };
            dfs(vertex1, vertex2, new Map(), []);
            return minPath;
        }
    }
```

**Comment by zrwusa** [comment]
> **Describe the bug**
> 
> "undirected-graph-typed": "^1.41.3"
> 
> const vertex = p.getIntersection(routes); const edges = p.getIntersectionNearestConnection( routes, vertex);
> 
> const graph = new UndirectedGraph(); for (const v of vertex) { graph.addVertex(v.name, v); };
> 
> for (const e of edges) { const [s,d] = e; graph.addEdge( s.name, d.name, d.distanceFromParent ); };
> 
> const result = graph.getAllPathsBetween('Intersection_1','Intersection_5',true)
> 
> **infinite loop when calling the getAllPathsBetween.**
> 
> i have a i9-10900k i stop the process after 5m.
> 
> **Desktop (please complete the following information):**
> 
> * OS: Win 11
> * * node v20.7.0
> 
> **Additional context** files: Vertex [SaltyGateStreetIntersections.json](https://github.com/zrwusa/data-structure-typed/files/13242883/SaltyGateStreetIntersections.json) Edge: [SaltyGateStreetConnections.json](https://github.com/zrwusa/data-structure-typed/files/13242882/SaltyGateStreetConnections.json)

In the worst case, if the graph is fully connected, meaning each vertex is connected to every other vertex, and there are no cycles, then the DFS algorithm will traverse all possible paths. This results in exponential time complexity. Typically, the time complexity in such a scenario can be represented as O(b^d), where b is the branching factor (the number of neighbors for each node), and d is the shortest path length between vertices.

If you're looking to find all possible paths between two points, you might want to consider the built-in Dijkstra's algorithm. If you're dealing with a graph that has negative weight paths, you can consider the built-in Floyd algorithm.

**Comment by zrwusa** [comment]
> in this function i commented this line `visiting.set(cur, false)`; , and i got the good result.
> 
> ```
> getMinPathBetween(v1, v2, isWeight) {
>         if (isWeight === undefined)
>             isWeight = false;
>         if (isWeight) {
>             const allPaths = this.getAllPathsBetween(v1, v2);
>             let min = Infinity;
>             let minIndex = -1;
>             let index = 0;
>             for (const path of allPaths) {
>                 const pathSumWeight = this.getPathSumWeight(path);
>                 if (pathSumWeight < min) {
>                     min = pathSumWeight;
>                     minIndex = index;
>                 }
>                 index++;
>             }
>             return allPaths[minIndex] || null;
>         }
>         else {
>             // BFS
>             let minPath = [];
>             const vertex1 = this._getVertex(v1);
>             const vertex2 = this._getVertex(v2);
>             if (!(vertex1 && vertex2)) {
>                 return [];
>             }
>             const dfs = (cur, dest, visiting, path) => {
>                 visiting.set(cur, true);
>                 if (cur === dest) {
>                     minPath = [vertex1, ...path];
>                     return;
>                 }
>                 const neighbors = this.getNeighbors(cur);
>                 for (const neighbor of neighbors) {
>                     if (!visiting.get(neighbor)) {
>                         path.push(neighbor);
>                         dfs(neighbor, dest, visiting, path);
>                         (0, utils_1.arrayRemove)(path, (vertex) => vertex === neighbor);               
>                     }
>                 }
>                 //visiting.set(cur, false);
>             };
>             dfs(vertex1, vertex2, new Map(), []);
>             return minPath;
>         }
>     }
> ```


As for your statement about commenting out '//visiting.set(cur, false);' to quickly retrieve all paths, it's actually a misconception. This step is necessary for backtracking. If you comment it out, you'll get incorrect results. It just happens that in your test data, the vertexes 1-5 are connected in sequence, and 1-5 is indeed the shortest path.

**Comment by zrwusa** [comment]
> **Describe the bug**
> 
> "undirected-graph-typed": "^1.41.3"
> 
> const vertex = p.getIntersection(routes); const edges = p.getIntersectionNearestConnection( routes, vertex);
> 
> const graph = new UndirectedGraph(); for (const v of vertex) { graph.addVertex(v.name, v); };
> 
> for (const e of edges) { const [s,d] = e; graph.addEdge( s.name, d.name, d.distanceFromParent ); };
> 
> const result = graph.getAllPathsBetween('Intersection_1','Intersection_5',true)
> 
> **infinite loop when calling the getAllPathsBetween.**
> 
> i have a i9-10900k i stop the process after 5m.
> 
> **Desktop (please complete the following information):**
> 
> * OS: Win 11
> * * node v20.7.0
> 
> **Additional context** files: Vertex [SaltyGateStreetIntersections.json](https://github.com/zrwusa/data-structure-typed/files/13242883/SaltyGateStreetIntersections.json) Edge: [SaltyGateStreetConnections.json](https://github.com/zrwusa/data-structure-typed/files/13242882/SaltyGateStreetConnections.json)

However, we have now added a parameter `limit` in version 1.41.9 to control the maximum number of possible paths, allowing you to set this parameter yourself to prevent excessively long waiting times.
