### ISSUE TITLE
Removing a vertex from a DirectedGraph doesn't remove it's edges

### ISSUE THREAD

**Issue by rkrump** [zrwusa/data-structure-typed#51]
**Describe the bug**
Removing a vertex from a DirectedGraph doesn't remove it's edges. Furthermore, these edges can then not be manually removed, since it doesn't find the referenced src/dest vertex.

**To Reproduce**

1. Create a graph containing the vertices "hello" and "world"
2. Add edge from "hello" to "world"
3. Remove "hello"
4. Edge "hello" to "world" still exists and cannot be removed

**Expected behavior**
Removing a vertex deletes all associated edges.

**Desktop**

- OS: Windows 10
- Engine NodeJS
- Version v18.17.1

**Additional notes**
Thanks for your work on this library <3

**Comment by zrwusa** [comment]
This bug was fixed in version 1.48.4.
