### ISSUE TITLE
Removing an edge of a DirectedGraph deletes additional edges

### ISSUE THREAD

**Issue by rkrump** [zrwusa/data-structure-typed#52]
**Describe the bug**
When using `deleteEdge(edge)` it deletes all outgoing edges of the source vertex and all incoming edges of destination vertex. This is not the case for `deleteEdgeSrcToDest(src, dest)`.

**To Reproduce**

1. Create a graph with the vertices "hello", "hi", "hey"
2. Create the edges "hello"->"hi", "hello"->"hey"
3. Delete the edge "hello"->"hi"
4. The edge "hello"->"hey" has been deleted even though that was not requested

**Expected behavior**
Only the specified edge should be deleted.

**Desktop (please complete the following information):**

- OS: Windows
- Engine NodeJS
- Version v18.17.1

**Additional context**
[directed-graph.ts#L201](https://github.com/zrwusa/data-structure-typed/blob/main/src/data-structures/graph/directed-graph.ts#L201)
[directed-graph.ts#L206](https://github.com/zrwusa/data-structure-typed/blob/main/src/data-structures/graph/directed-graph.ts#L206)

**Comment by zrwusa** [comment]
This bug was fixed in version 1.48.4.
