### ISSUE TITLE
Request fix "at" method in Queue

### ISSUE THREAD

**Issue by vadymsushkovdev** [zrwusa/data-structure-typed#84]
Since you use "offset" in the shift method for optimization purposes, accessing a variable by index in the "at" method should also take into account the variable's position relative to the offset.

Path: "data-structure-typed/src/data-structures/queue/queue.ts".

Fix:
```
  at(index: number): E | undefined {
    return this.elements[index + this._offset];
  }
```

**Comment by zrwusa** [comment]
This issue has been resolved in version 1.52.0
