### ISSUE TITLE
TreeMultiMap and TreeMultiMapNode API docs are currently a 404

### ISSUE THREAD

**Issue by matthew-dean** [zrwusa/data-structure-typed#87]
https://data-structure-typed-docs.vercel.app/classes/TreeMultiMap.html
https://data-structure-typed-docs.vercel.app/classes/TreeMultiMapNode.html

**Comment by zrwusa** [comment]
> https://data-structure-typed-docs.vercel.app/classes/TreeMultiMap.html https://data-structure-typed-docs.vercel.app/classes/TreeMultiMapNode.html

We have now redeployed the document site. Please check if it is accessible.
