### ISSUE TITLE
Max Length for Deque

### ISSUE THREAD

**Issue by geyang** [zrwusa/data-structure-typed#89]
Is there a way to specify the maximum length for the Deque?

For instance, in python:

```python

dq = dequeue(maxlen=10)

for i in range(20):
     dq.push(i)

assert len(dq) == 10, "length is capped at `maxlen`"
```

**Comment by zrwusa** [comment]
> Is there a way to specify the maximum length for the Deque?
> 
> For instance, in python:
> 
> ```python
> dq = dequeue(maxlen=10)
> 
> for i in range(20):
>      dq.push(i)
> 
> assert len(dq) == 10, "length is capped at `maxlen`"
> ```

In response to your valuable feedback, we have incorporated a maxLen configuration parameter into the Deque implementation. To leverage this new functionality, kindly download the latest version, v1.52.1.
