### ISSUE TITLE
Queue: More control over flush cutoff for memory performance

### ISSUE THREAD

**Issue by augmentmoogi** [zrwusa/data-structure-typed#91]
**Is your feature request related to a problem? Please describe.**

The Queue implementation assumes size can be double. 
In an effort to get O(1) we keep an offset and check if offset * 2 < length
However that means that the queue memory size can grow to be double which might not be desired. 
If I want to keep 5K elements, the flush implementation can make it hold 10K elements before actually flushing. 

**Describe the solution you'd like**
I would like to have more control.. for example, to be able to specify a flat amount of items as a limit after which the queue should flush. 

**Describe alternatives you've considered**
An explicit flush option would also be nice - as you expose the "offset" I can basically call "flush" myself keeping the "options" for the queue simple. 

**Additional context**
A common use case is to keep queues at a certain size. The current implementation guarantees we will get at least twice the memory (assuming all items have the same consumption)
It makes it hard to effectively control the memory usage of the data structure.

**Comment by zrwusa** [comment]
Your suggestion was very helpful. We've added the compact method to the Queue data structure and included the autoCompactRatio configuration option as you suggested, allowing you to control automatic memory release proportionally. Please update to version 1.52.2 to use this feature. 

In the future, we plan to extend this functionality to Deque.
