### ISSUE TITLE
[Trie] `getWords` returns invalid results even when the whole prefix doesn't match.

### ISSUE THREAD

**Issue by sjunepark** [zrwusa/data-structure-typed#93]
**Describe the bug**

Trie's `getWords` is returning invalid results even when the whole prefix doesn't match.
I'll submit a pull request, please review.
Thanks.

**To Reproduce**

I've added failing test cases in my [fork](https://github.com/sjunepark/data-structure-typed/tree/trie-issue).

```ts
// Works as expected
  it('Get no words when prefix not found, with no match from the first character', () => {
    trie.add('apple');
    trie.add('appetizer');
    trie.add('banana');
    const words = trie.getWords('cd');
    expect(words).toEqual([]);
  });

// Fails. Returns invalid result
// ```
// [
//   "abpple",
//   "abppetizer"
// ]
// ```
  it('Get no words when prefix not found, with no match from the second character', () => {
    trie.add('apple');
    trie.add('appetizer');
    trie.add('banana');
    const words = trie.getWords('ab');
    expect(words).toEqual([]);
  });
```

**Expected behavior**

Should return an empty array, `[]`

**Comment by zrwusa** [comment]
Thank you, Sjunepark, for carefully identifying the issue and contributing. Even though it's a small feature, your workflow is very professional. We have released the version with your bug fixing code. Please use and test version 1.52.3.
